### ISSUE TITLE
Error { kind: InvalidOperation, detail: "filter requires time, but only received a date", name: "<string>", line: 1 }

### ISSUE THREAD

**Issue by nbittich** [mitsuhiko/minijinja#397] opened 2024-01-18 12:45 UTC
## Description
Trying to use the datetimeformat filter with  default format and timezone.
 
[What happened]

Trying to use the datetimeformat filter using default format & timezone. 
The timestamp below comes from the example in chrono doc (https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDateTime.html#method.from_timestamp_millis)

## Reproduction steps

1. Add the dependencies (using latest, 1.0.11):

```toml
minijinja = { workspace = true, default-features = false, features = [

  "builtins",
  "macros",
  "speedups",
  "urlencode",
] }
minijinja-contrib = { workspace = true, features = ["datetime", "timezone", "time-tz", "time"] }
chrono = { workspace = true, features = ["serde"] }

```

2. Make a function to create the jinja engine:

```rust

fn get_jinja_engine<'a>() -> Result<&'a Environment<'static>, Box<dyn Error>> {
    let engine = {
        if JINJA_ENGINE.get().is_none() {
            let mut env = Environment::new();
            env.add_global("TIMEZONE", "Europe/Brussels");
            env.add_global("DATETIME_FORMAT", "[day]/[month]/[year] [hour]:[minute]");
            env.add_global("DATE_FORMAT", "[day]/[month]/[year]");
            
            minijinja_contrib::add_to_environment(&mut env);
            JINJA_ENGINE
                .set(env)
                .map_err(|_env| "could not setup jinja".to_string())?;
        }
        JINJA_ENGINE
            .get()
            .ok_or("could not extract engine from cell")
    }?;
    Ok(engine)
}
```

3. Make a simple unit test:

```rust
    #[tokio::test]
    async fn test_date_and_time() {
        #[derive(Serialize, Deserialize)]
        struct Whatever {
            dt: NaiveDateTime,
            d: NaiveDate,
        }

        let ctx = Whatever {
            dt: NaiveDateTime::from_timestamp_millis(1662921288000).unwrap(),
            d: NaiveDate::from_ymd_opt(2024, 1, 1).unwrap(),
        };

         assert_eq!(
                  "01/09/2022 18:34",
                  engine
                      .render_str(r#"{{ dt|datetimeformat }}"#, ctx)
                      .unwrap()
              );
    }
}
```

Additional helpful information:

- Version of minijinja: 1.0.11
- Version of rustc: 1.75
- Operating system and version: PopOS 22.0.4

## What did you expect

I should get the date format like e.g `01/09/2022 18:34`

**Comment by mitsuhiko** [comment] 2024-01-19 22:29
Duplicate of #396

**Closed by mitsuhiko** 2024-01-19 22:29 UTC
