### ISSUE TITLE
Suggest enhancing the custom dynamic asynchronous tag function

### ISSUE THREAD

**Issue by sunkaifei** [mitsuhiko/minijinja#622] opened 2024-10-28 03:01 UTC
Specifically referring to the JAVA freemarker template function, it roughly means that all data can be called through tags, so that most data and lists are implemented through tags. This eliminates the need to write various parameters and parameters that need to be called in the controller. The advantage of tags is that the entire site can be called, and each page of the controller page does not need to write various parameters to match the template call. It can be implemented through tags, and even if it is not called, it will not be executed. However, currently the controller must implement a functional template to call it. If the controller is not called, it still needs to be executed once

**Comment by mitsuhiko** [comment] 2024-10-28 22:29
I'm not familiar with FreeMaker and I'm also not sure how it relates to MiniJinja.  Can you maybe explain this by providing an example of what you want things to work / what you are trying to accomplish to better illustrate your request?

**Comment by sunkaifei** [comment] 2024-10-29 06:19
For example, our current page template output asynchronous content needs to be written in the controller:
```
let ctx = context!(
        title => "title",
    );
```
Then when calling this tag in the template, other controllers need to call it again, especially when reading asynchronous content from the database, which is even more complex to call.

If multiple asynchronous data are called in a controller, it can only be output in the current page template. If not output, all functions will still be executed in the controller if there is no asynchronous data called in the template

Here is an example of my article module：

```
 public Object paginate(Map params) {
        int pageNum = this.getPageNum(params);
        int pageSize = this.getPageSize(params);
        String title = getParam(params, "title");
        Long columnId = getLongParam(params, "columnId");
        Long userId = getLongParam(params, "userId");
        String sort = getParam(params, "sort");
        String order = getParam(params, "order");
        int status = getStatusParam(params,"status");
        int isaudit = getStatusParam(params,"isaudit");
        int deleted = getDeletedTopic(params);
        Article article = new Article();
        article.setColumnId(columnId);
        article.setUserId(userId);
        article.setStatus(String.valueOf(status));
        article.setTitle(title);
        article.setIsaudit(String.valueOf(isaudit));
        article.setDeleted(String.valueOf(deleted));
        return articleService.selectPager(article, pageNum, pageSize, sort, order);
    }

    public Object recommend(Map params) {
        int pageNum = this.getPageNum(params);
        int pageSize = this.getPageSize(params);
        Long infoId = getLongParam(params, "infoId");
        Long groupId = getLongParam(params, "groupId");
        String sort = getParam(params, "sort");
        String order = getParam(params, "order");
        int type = getParamInt(params,"type");
        int tj = getParamInt(params,"tj");
        ArticleRecommend topicRecommend = new ArticleRecommend();
        topicRecommend.setGroupId(groupId);
        topicRecommend.setContentTypeId(type);
        topicRecommend.setContentId(infoId);
        topicRecommend.setRecommend(tj);
        return articleRecommendService.selectPager(topicRecommend, pageNum, pageSize, sort, order);
    }

    public Object classify(Map params) {
        String title = getParam(params, "title");
        Long columnId = getLongParam(params, "columnId");
        Long groupId = getLongParam(params, "groupId");
        String status = getParam(params,"status");
        ArticleColumn articleColumn = new ArticleColumn();
        if(!StrUtils.isEmpty(title) && columnId == null && groupId==null){
            return null;
        }
        articleColumn.setColumnName(title);
        articleColumn.setStatus(status);
        return articleColumnService.selectColumnList(articleColumn);
    }

    /**
     * 文章分类详细信息
     *
     * @param params
     * @return
     */
    public Object columninfo(Map params) {
        Long id = getLongParam(params, "id");
        ArticleColumnResponse column = null;
        if(id != null){
            column = articleColumnService.findColumnById(id);
        }
        return column;
    }

    /**
     * 文章详细信息
     *
     * @param params
     * @return
     */
    public Object info(Map params) {
        Long id = getLongParam(params, "id");
        ArticleResponse article = null;
        if(id != null){
            article = articleService.findById(id);
        }
        return article;
    }

    public Object comment(Map params) {
        int pageNum = this.getPageNum(params);
        int pageSize = this.getPageSize(params);
        Long userId = getLongParam(params, "userId");
        Long topicId = getLongParam(params, "topicId");
        Long referId = getLongParam(params, "referId");
        String sort = getParam(params, "sort");
        String order = getParam(params, "order");
        int status = getStatusParam(params,"status");
        int deleted = getDeletedTopic(params);
        ArticleComment topicComment = new ArticleComment();
        if(referId == null && userId == null && topicId==null){
            return null;
        }
        topicComment.setUserId(userId);
        topicComment.setTopicId(topicId);
        topicComment.setReferId(referId);
        topicComment.setStatus(status);
        topicComment.setDeleted(deleted);
        return articleCommentService.selectPager(topicComment, pageNum, pageSize, sort, order);
    }

    public Object reComment(Map params) {
        int pageNum = this.getPageNum(params);
        int pageSize = this.getPageSize(params);
        Long userId = getLongParam(params, "userId");
        Long topicId = getLongParam(params, "topicId");
        Long referId = getLongParam(params, "referId");
        String sort = getParam(params, "sort");
        String order = getParam(params, "order");
        int status = getStatusParam(params,"status");
        int deleted = getDeletedTopic(params);
        ArticleComment topicComment = new ArticleComment();
        if(referId == null && userId == null && topicId==null){
            return null;
        }
        topicComment.setUserId(userId);
        topicComment.setTopicId(topicId);
        topicComment.setReferId(referId);
        topicComment.setStatus(status);
        topicComment.setDeleted(deleted);
        return articleCommentService.selectPager(topicComment, pageNum, pageSize, sort, order);
    }

    /**
     * 随机标签列表
     *
     * @param params
     * @return
     */
    public Object randList(Map params) {
        int pageSize = getParamInt(params, "pageSize");
        return articleService.selectRandArticleList(pageSize);
    }

```
This is a globally set label

```
configuration.setSharedVariable("fly_article", articleDirective);
```

**Comment by sunkaifei** [comment] 2024-10-29 06:29
Call in template

```

[@fly_article method="paginate" status="2" audit="0"]
                [#list paginate.rows as list]
                       ${list.title!}
                [/#list]
[/@fly_article]

```
Method: You can specify which tags in the calling module to call
 status="2" audit="0"  These are the parameters for optional filling

![Uploading 微信截图_20241029142838.png…]()

**Comment by sunkaifei** [comment] 2024-10-29 06:41
The purpose of all tagging in this way is that all controller pages can call these tags to achieve the desired results. If the tags are not called in the template, asynchronous data that needs to be called will not be executed, greatly increasing the efficiency of controller execution。

Another advantage is that, for example, a popular news list, I can call it from any page without adding asynchronous methods to the controller that require calling data,

The called data can return the desired content based on the passed parameters, so as long as the tags are written during program development, the template development can be directly handed over to the front-end in the future


**Because I used translation software to translate the reply content, I don't know if the author can understand the meaning I am expressing?**

**Comment by mitsuhiko** [comment] 2024-10-29 07:59
This template engine is written in Rust, how does Java enter the picture?  Also the template code you pasted does not appear to be MiniJinja either.

**Comment by sunkaifei** [comment] 2024-10-29 08:08
The partially demonstrated code is in Java, which is actually similar to the current MiniJinja tags. The only difference is that customizing asynchronous tags is more complex, so it can be simplified to support asynchronous tags like writing synchronous tags

**Comment by mitsuhiko** [comment] 2024-10-29 08:30
It's very hard for me to engage here because I really do not understand what you are trying to accomplish in the context of minijinja :(

**Comment by sunkaifei** [comment] 2024-10-29 08:41
Because you mentioned an example at the beginning, I sent a demonstration of the Java code above as an explanation, mainly to suggest better support for custom asynchronous tags

**Comment by mitsuhiko** [comment] 2024-10-29 11:45
I'm going to close this ticket because I do not understand the problem here.  Feel free to make a new ticket with your feature request but by using minijinja template code and rust code to make it clear what the issue is you are trying to solve.

**Closed by mitsuhiko** 2024-10-29 11:45 UTC
Labels: needs-more-information
